#!/bin/bash

set -e -u -o pipefail

cd "$(dirname "$0")"

# Path to the backup
dcimpath=$1

./make-file-list | while IFS=$'\t' read -r zalbum zpath; do
    source="${dcimpath}/${zpath}"
    if [[ -f "${source}" ]]; then
        # echo "PATH: '$zpath' → ALBUM: '$zalbum'"
        dest="${dcimpath}/Albums/${zalbum}/"
        mkdir -p "${dest}"
        \cp --verbose --backup=numbered "${source}" "${dest}"
    else
        echo "${source} does not exist"
    fi
done
