#!/bin/bash

set -e -u -o pipefail

# arg1 is path to Photos.sqlite
Photossqlite="$1"

sqlite3 -separator $'\t' "${Photossqlite}" < select.sql | awk '
BEGIN{OFS=FS="\t"}
!$1 { $1="Untitled album" }
{ gsub("/", "_", $1) }
$1 && $2 && NF==2
'
